Switch to an older version of VegaLite
Was getting the following error on the web server:

```
IOError: could not spawn
setenv(`/root/.julia/artifacts/a42f5c72a500a8683c08a5e818d27a104fc9cd5a/bin/node
/root/.julia/artifacts/705eb8c5493e999f55641b8469b46ba151f079c3/vl2vg.js`;
dir="/root/.julia/artifacts/705eb8c5493e999f55641b8469b46ba151f079c3"):
no such file or directory (ENOENT)
```